<a href="https://colab.research.google.com/github/lizzieeli/CS378_Research_Project/blob/main/CS378_Research_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:\n", arr)

arr_transpose = arr.T
print("Transpose of the array:\n", arr_transpose)

Original array:
 [[1 2 3]
 [4 5 6]]
Transpose of the array:
 [[1 4]
 [2 5]
 [3 6]]
